# Generated by Django 3.0.8 on 2020-11-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='user', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
